project_id = "lsyzbxogbjourwgchisg"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.customer-request-otp]
verify_jwt = false

[functions.customer-verify-otp]
verify_jwt = false

[functions.customer-portal-data]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-inbound]
verify_jwt = false

[functions.whatsapp-status-update]
verify_jwt = false
