-- Insert comprehensive Gold Declaration content blocks for Zenith Finance
INSERT INTO print_content_blocks (client_id, block_type, content_english, content_tamil, display_order, is_active)
VALUES
  -- Gold Declarations (6 statements)
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'gold_declaration', 'Ownership: I confirm that the gold ornaments pledged by me belong solely to me/my family and are my absolute property.', 'உரிமை: நான் அடகு வைத்துள்ள தங்க நகைகள் எனக்கு/எனது குடும்பத்திற்கு மட்டுமே சொந்தமானவை மற்றும் எனது முழுமையான சொத்து என்று உறுதி அளிக்கிறேன்.', 1, true),
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'gold_declaration', 'No Encumbrance: I declare that these ornaments are free from any prior mortgage, loan, court attachment, or legal dispute.', 'வில்லங்கமின்மை: இந்த நகைகள் மீது முந்தைய அடமானம், கடன், நீதிமன்ற ஜப்தி அல்லது சட்டரீதியான வில்லங்கம் ஏதும் இல்லை என்று அறிவிக்கிறேன்.', 2, true),
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'gold_declaration', 'Legality: I solemnly declare that these ornaments are not stolen property and are not involved in any police case or illegal activity. I take full responsibility if any such claim arises.', 'சட்டப்பூர்வம்: இந்த நகைகள் திருடப்பட்டவை அல்ல என்றும், எந்தவித காவல் துறை வழக்கு அல்லது சட்டவிரோத செயல்களிலும் சம்பந்தப்பட்டவை அல்ல என்றும் உறுதியளிக்கிறேன். அவ்வாறு ஏதேனும் புகார் எழுந்தால் அதற்கு நானே முழு பொறுப்பேற்கிறேன்.', 3, true),
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'gold_declaration', 'Quality Verification: I am satisfied with the purity check, weight appraisal, and valuation done by the company in my presence. I agree that if any defect or spurious gold is found at a later stage, I am liable to replace it or repay the loan amount immediately.', 'தரம் சரிபார்ப்பு: நிறுவனம் எனது முன்னிலையில் செய்த தங்கத்தின் தரம், எடை மற்றும் மதிப்பீட்டில் எனக்கு முழு திருப்தி உள்ளது. பின்னர் ஏதேனும் குறைபாடு அல்லது போலி தங்கம் கண்டறியப்பட்டால், அதை மாற்றிக்கொடுக்கவோ அல்லது கடன் தொகையை உடனடியாக திருப்பிச் செலுத்தவோ நான் கடமைப்பட்டுள்ளேன்.', 4, true),
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'gold_declaration', 'Default & Auction: I understand that if I fail to repay the principal and interest within the agreed tenure, Zenith Finance has the full right to sell or auction these ornaments to recover the dues without further notice to me.', 'தவணை தவறுதல் & ஏலம்: ஒப்புக்கொள்ளப்பட்ட காலக்கெடுவுக்குள் அசல் மற்றும் வட்டியுடன் கடனைத் திருப்பிச் செலுத்தத் தவறினால், எனக்கு முன்னறிவிப்பு ஏதுமின்றி நிலுவைத் தொகையை மீட்க இந்த நகைகளை விற்கவோ அல்லது ஏலம் விடவோ Zenith Finance நிறுவனத்திற்கு முழு உரிமை உண்டு என்பதை நான் அறிவேன்.', 5, true),
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'gold_declaration', 'Contact Details: The residential address and mobile number provided by me are correct. I agree to inform the branch immediately if there is any change in my address or contact details.', 'தொடர்பு விவரங்கள்: நான் வழங்கிய வீட்டு முகவரி மற்றும் அலைபேசி எண் சரியானவை. எனது முகவரி அல்லது தொடர்பு விவரங்களில் ஏதேனும் மாற்றம் இருந்தால் உடனடியாக கிளைக்கு தெரிவிப்பேன் என்று ஒப்புக்கொள்கிறேன்.', 6, true),
  -- Warning
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'warning', 'Warning: Any false declaration may result in legal action, forfeiture of pledged items, and criminal prosecution.', 'எச்சரிக்கை: தவறான அறிவிப்பு சட்ட நடவடிக்கை, அடமான பொருட்களை இழப்பு மற்றும் குற்றவியல் வழக்கு தொடரப்படலாம்.', 1, true),
  -- Acknowledgment
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'acknowledgment', 'I have read and understood all the above declarations. I confirm that all information provided is true and correct to the best of my knowledge.', 'மேலே குறிப்பிடப்பட்ட அனைத்து அறிவிப்புகளையும் படித்து புரிந்துகொண்டேன். வழங்கப்பட்ட அனைத்து தகவல்களும் எனது அறிவுக்கு ஏற்ப உண்மையானவை மற்றும் சரியானவை என்று உறுதிப்படுத்துகிறேன்.', 1, true),
  -- Signature Labels
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'signature_labels', 'Customer Signature', 'வாடிக்கையாளர் கையொப்பம்', 1, true),
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'signature_labels', 'Witness Signature', 'சாட்சி கையொப்பம்', 2, true),
  ('2abc571d-ce56-4e32-ac8e-0761fafe8999', 'signature_labels', 'Authorized Signature', 'அங்கீகரிக்கப்பட்ட கையொப்பம்', 3, true);